spring:
  application:
    name: security
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##DS
    password: DS
    driver-class-name: oracle.jdbc.driver.OracleDriver
  web:
    resources:
      static-locations: file:uploads/
  mvc:
    static-path-pattern: /uploads/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 80
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
  type-aliases-package: com.ds.security.member.model.dto, com.ds.security.board.model.dto
  mapper-locations: classpath:mapper/**/*.xml
jwt:
  secret: D9uLKVc4FE0IEheN3pLLEb8GKhHRsG8cdOxazHnEkRm3CGAeB+xVbt8Dbob1QhRB